### PR TITLE
Netbox Support

### PR DESCRIPTION
**Pull request by m4c3**
ive added all things needed for the support of netbox
right now the groups feature is not supported, cause i wasnt sure which netbox setting i should use for this.
tests are completely missing, will be added when the settings injection wiring works.. 

activation of the plugin for now via swapping out Phpipam for Netbox in line 5 of ipam_http_config.ru

### CODE REVIEW

**Comment by grizzthedj** [comment]
Thank you @m4c3. That was fast :)

Could you change the destination branch to `develop` for this PR, and also squash all commits into one?

I will need some time to review and test this, as well as regression testing of the phpIPAM. Did you have any issues installing or setting up Netbox in a local dev env? Any feedback on issues you may have had would be great.

**Comment by m4c3** [comment]
Branch is changed to develop, commits are squashed.

ive used the [netbox docker image](https://github.com/netbox-community/netbox-docker). thats really easy to set up, but for https support an additional/external reverseproxy is needed. but there are some bugs in netbox ui that redirects sometimes go to http://127.0.0.1:8000 - but the api works fine. 

regarding the tests. my testing attemts failed cause the connection settings from the config file are not existing. 
i think the client classes have to be rewritten to use attr_reader. maybe have a look how this is done in the other smart proxys :)

**Review by grizzthedj — COMMENTED** [review]
@m4c3 - I have started testing this (not finished yet), and so far everything seems to be working well. Setting up Netbox using Docker was really fast and easy(a lot easier than phpIPAM was). 

In terms of the Groups, there is actually a component in Netbox called `Tenant` that allows for grouping of prefixes/subnets(as well as other components). This is the same concept as a `Section` in phpIPAM. I think we can use the `Tenant` as the External IPAM group for Netbox. More info on this [here](https://netbox.readthedocs.io/en/stable/core-functionality/tenancy/).

If the same prefix/subnet exists in 2 different Tenants(for example), we want to be able to pull IP's from each of these prefixes/subnets individually. I suspect there should be a way to specify the Tenant, when pulling, writing and deleting IP's via the API. 

Would you able to add this as well?

**Comment by grizzthedj** [comment]
@m4c3 - A friendly ping to see if you have looked into the Tenant stuff in Netbox. Let me know if you have the bandwidth to do this. If you don't, just let me know, and I will merge this PR as is, and will look into the Tenant stuff myself. We also need the Netbox integration within the next few months as well.

**Comment by m4c3** [comment]
Tennant support is ready

**Comment by grizzthedj** [comment]
@m4c3 - This is great! I will start testing tomorrow.

**Comment by grizzthedj** [comment]
@m4c3 - I have done a fair bit of testing here and there seems to be an issue, not with your code, but with the Group/Tenant implementation. This is my bad.

I was under the impression that a `Tenant` was a way to group subnets and IP's in Netbox. Unfortunately, this is not the case. For example, assume there are 2 Tenants (`TenantA` and `TenantB`), each containing a prefix of `100.10.10.0/29`. If I add the IP address `100.10.10.1` to the prefix in `TenantA`, then I get the next available IP from the same prefix in TenantB, I get `100.10.10.2`, even though I never added the IP to the prefix in `TenantB`. NetBox sees the IP of `100.10.10.1` as "used" in either prefix, because they are both sitting in the global space.

It appears that IPs and prefixes are namespaced ONLY by `VRF`, so if we want to have support for Netbox "groups", we need to use VRFs for External IPAM Groups, not Tenants. 

My apologies for making the wrong assumption here, without looking into this in more detail. Let me know if you are able to make this change. I can help if needed.

**Pull request merged**
